name: LAP
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core:
  firebase_auth:
  #  intl: ^0.16.1
  jaguar_jwt: ^2.1.6
  http: any
  flutter_secure_storage: ^3.3.1+1
  json_annotation: ^2.4.0
  progress_dialog: ^1.2.4
  cupertino_icons: ^0.1.3
  permission_handler: ^5.1.0+2
  qrscan: ^0.2.22
  image_picker: ^0.6.7+22
  image_cropper: ^1.4.0
  image_gallery_saver: ^1.6.7
  firebase_messaging: ^7.0.3
  device_info: ^2.0.0
  page_transition: ^1.1.6
  simple_animations: ^1.3.3
  awesome_dialog: ^0.1.0
  provider: ^5.0.0
  flutter_linkify: ^5.0.2
  intl_phone_number_input: ^0.6.0
  pin_code_fields: ^7.2.0
  auto_size_text: ^2.1.0
  barcode_scan: ^2.0.1
  qr_flutter: ^3.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.17.0

json_serializable: ^3.0.0
build_runner: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logos/
    - assets/icons/
#    - assets/logos/logo.png
#    - assets/logos/LogoLAP.png
#    - assets/icons/transfer.png
#    - assets/icons/history.png
#    - assets/icons/electric.png
#    - assets/icons/billpayment.png
#    - assets/icons/history.png
#    - assets/icons/card.png
#    - assets/icons/water.png
#    - assets/icons/phone.png
#    - assets/icons/tax.png
#    - assets/icons/leasing.png
#    - assets/icons/topup.png
#    - assets/icons/LTC.png
#    - assets/icons/UNITEL.png
#    - assets/icons/UNITEL.jpg
#    - assets/icons/ETL.png
#    - assets/icons/TPLUS.png
#    - assets/icons/SOUVANHNY.jpg
#    - assets/icons/AEON.jpg
#    - assets/icons/KRUNGSRI.png
#    - assets/icons/succeeded.png
#    - assets/icons/failed.png
#    - assets/icons/income.png
#    - assets/icons/outcome.png
#    - assets/icons/payment.png
#    - assets/icons/payment-01.png
#    - assets/icons/lapnet.png
#    - assets/icons/lapnetForQR.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
fonts:
  - family: OpenSans
    fonts:
      - asset: assets/fonts/OpenSans.ttf
  - family: NotoSansLao
    fonts:
      - asset: assets/fonts/NotoSansLao.ttf

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages